import { defineConfig } from 'vitepress'
import llmstxt from 'vitepress-plugin-llms'
// Generated by TypeDoc (predocs hook) from src/ TSDoc — the API reference is
// the single source of truth for the programmatic surface. This file is
// gitignored; it always exists at build time because `typedoc` runs first.
import typedocSidebar from '../reference/api/typedoc-sidebar.json'

const SITE_URL = 'https://max-health-inc.github.io'
const SITE_BASE = '/prefab/'

export default defineConfig({
  title: '@maxhealth.tech/prefab',
  description:
    'The TypeScript full-stack framework for MCP app UIs. Author server-side, ship JSON, render anywhere. A superset of Python prefab-ui.',

  base: SITE_BASE,
  cleanUrls: true,
  lastUpdated: true,

  // The generated rx API emits `variables/INDEX.md` (the INDEX scope variable).
  // On case-insensitive filesystems its clean URL collides with the reserved
  // `index` route, a false positive in the dead-link checker (it resolves fine
  // on Linux/CI). Scope the ignore narrowly to that generated page.
  ignoreDeadLinks: [/variables\/index$/i],

  // ── SEO ──────────────────────────────────────────────────────────────────
  sitemap: { hostname: `${SITE_URL}${SITE_BASE}` },

  // Add v-pre to inline <code> so {{ }} isn't parsed as Vue interpolation.
  // Fenced code blocks already get v-pre via Shiki, but inline code does not.
  markdown: {
    config: (md) => {
      const defaultCodeInline = md.renderer.rules.code_inline!
      md.renderer.rules.code_inline = (...args) => {
        return defaultCodeInline(...args).replace('<code>', '<code v-pre>')
      }
    },
  },

  head: [
    ['link', { rel: 'icon', href: '/prefab/favicon.ico' }],
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/prefab/brand/logo.svg' }],
    // LLM and crawler discovery
    ['link', { rel: 'sitemap', type: 'application/xml', href: `${SITE_URL}${SITE_BASE}sitemap.xml` }],
    ['link', { rel: 'index', type: 'text/markdown', href: `${SITE_URL}${SITE_BASE}llms.txt`, title: 'LLM-friendly index of Prefab docs' }],
    ['link', { rel: 'alternate', type: 'text/markdown', href: `${SITE_URL}${SITE_BASE}llms-full.txt`, title: 'Full LLM-friendly Prefab docs corpus' }],
    // Open Graph
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: '@maxhealth.tech/prefab' }],
    ['meta', { property: 'og:title', content: '@maxhealth.tech/prefab — Declarative UI for MCP Apps' }],
    ['meta', { property: 'og:description', content: '115+ TypeScript components, reactive state, zero-framework renderer for MCP Apps. A superset of Python prefab-ui.' }],
    ['meta', { property: 'og:url', content: `${SITE_URL}${SITE_BASE}` }],
    // Twitter
    ['meta', { name: 'twitter:card', content: 'summary' }],
    ['meta', { name: 'twitter:title', content: '@maxhealth.tech/prefab — Declarative UI for MCP Apps' }],
    ['meta', { name: 'twitter:description', content: '115+ TypeScript components, reactive state, zero-framework renderer for MCP Apps.' }],
  ],

  // ── Transformations ──────────────────────────────────────────────────────
  transformPageData(pageData) {
    // Canonical URL for every page
    const canonicalUrl = `${SITE_URL}${SITE_BASE}${pageData.relativePath}`
      .replace(/index\.md$/, '')
      .replace(/\.md$/, '')
    pageData.frontmatter.head ??= []
    pageData.frontmatter.head.push(['link', { rel: 'canonical', href: canonicalUrl }])
    pageData.frontmatter.head.push(['meta', { property: 'og:url', content: canonicalUrl }])

    // Per-page OG tags from frontmatter description
    if (pageData.frontmatter.description) {
      pageData.frontmatter.head.push(
        ['meta', { property: 'og:description', content: pageData.frontmatter.description }],
      )
    }
  },

  // Ensure static public/ apps (demo, playground) are served in dev mode.
  // VitePress's SPA router intercepts /demo/ and /playground/ as client routes;
  // this middleware rewrites them to the actual index.html before that happens.
  vite: {
    plugins: [
      llmstxt(),
      {
        name: 'serve-public-apps',
        configureServer(server) {
          server.middlewares.use((req, _res, next) => {
            const publicApps = ['/prefab/demo/', '/prefab/playground/']
            if (req.url && publicApps.includes(req.url)) {
              req.url = req.url.replace(/\/$/, '/index.html')
            }
            next()
          })
        },
      },
    ],
  },

  themeConfig: {
    logo: { light: '/brand/logo.svg', dark: '/brand/logo-light.svg' },

    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Reference', link: '/reference/components' },
      { text: 'Demo', link: '/demo/', target: '_blank' },
      { text: 'Playground', link: '/playground/', target: '_blank' },
      {
        text: 'Links',
        items: [
          {
            text: 'npm',
            link: 'https://www.npmjs.com/package/@maxhealth.tech/prefab',
          },
          {
            text: 'Changelog',
            link: 'https://github.com/Max-Health-Inc/prefab/blob/main/CHANGELOG.md',
          },
        ],
      },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Introduction',
          items: [
            { text: 'Getting Started', link: '/guide/getting-started' },
          ],
        },
        {
          text: 'Concepts',
          items: [
            { text: 'Components', link: '/guide/components' },
            { text: 'Actions', link: '/guide/actions' },
            { text: 'Reactive Expressions', link: '/guide/rx' },
            { text: 'Signals & Collections', link: '/guide/rx#signals--collections' },
            { text: 'Auto-Renderers', link: '/guide/auto-renderers' },
          ],
        },
        {
          text: 'Integration',
          items: [
            { text: 'MCP Display Helpers', link: '/guide/mcp-display' },
            { text: 'Browser Renderer', link: '/guide/renderer' },
            { text: 'PostMessage Bridge', link: '/guide/bridge' },
          ],
        },
      ],

      '/reference/': [
        {
          text: 'Reference',
          items: [
            { text: 'Components', link: '/reference/components' },
            { text: 'Wire Format', link: '/reference/wire-format' },
            { text: 'MCP Apps', link: '/reference/mcp-apps' },
          ],
        },
        {
          // Generated from src/ TSDoc by TypeDoc — the programmatic API surface
          // (actions, rx, mcp, auto, renderer/bridge).
          text: 'API (from source)',
          items: typedocSidebar,
        },
      ],
    },

    socialLinks: [
      {
        icon: 'github',
        link: 'https://github.com/Max-Health-Inc/prefab',
      },
    ],

    editLink: {
      pattern:
        'https://github.com/Max-Health-Inc/prefab/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },

    search: {
      provider: 'local',
    },

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © 2026-present Max Health Inc.',
    },
  },
})
